version: "2"
services:
  app:
    image: jc21/node
    ports:
      - 8080:80
      - 8081:81
      - 8443:443
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - .:/srv/app
    depends_on:
      - db
    links:
      - db
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js
  db:
    image: mariadb:10.3.7
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/npm.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initial-sql:/docker-entrypoint-initdb.d

